package settings;

public enum EnumUserPermissions {
	
	USER_PERMISSION_PROJECT_ADD,
	USER_PERMISSION_PROJECT_EDIT,
	USER_PERMISSION_PROJECT_DELETE,
	
	USER_PERMISSION_BUG_ADD,
	USER_PERMISSION_BUG_EDIT,
	USER_PERMISSION_BUG_DELETE

}
